### ISSUE TITLE
Replace if current tab isn't modified & saved only

### ISSUE THREAD

**Issue by HapLifeMan** [alexfu/atom-replace-pane#2]
Hello,

Can you add the setting that allow us to open a new file into the same pane only if the current file has not been modified before?
It's like in Sublime Text and this feature is very cool! Atom open a pane for each new file :(

AND

Please don't force save before replacing because I've the sftp-sync and it upload each time...

Thanks!

**Comment by stevemoser** [comment]
@HapLifeMan You might be looking for this: https://atom.io/packages/sublime-panes

**Comment by HapLifeMan** [comment]
Yes of course! Thank you so much!
